---
# SecretStore - defines how to connect to AWS Secrets Manager
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secretsmanager
  namespace: default
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        serviceAccount:
          name: external-secrets
---
# ExternalSecret - defines which secrets to sync and how
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sample-app-secret
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: sample-app-secret
    type: Opaque
  data:
  - secretKey: username
    remoteRef:
      key: test-dev2/sample-app-secret
      property: username
  - secretKey: password
    remoteRef:
      key: test-dev2/sample-app-secret
      property: password
  - secretKey: api-key
    remoteRef:
      key: test-dev2/sample-app-secret
      property: api_key
  - secretKey: database-host
    remoteRef:
      key: test-dev2/sample-app-secret
      property: database.host
  - secretKey: database-port
    remoteRef:
      key: test-dev2/sample-app-secret
      property: database.port
  - secretKey: database-name
    remoteRef:
      key: test-dev2/sample-app-secret
      property: database.name
  - secretKey: database-username
    remoteRef:
      key: test-dev2/sample-app-secret
      property: database.username
  - secretKey: database-password
    remoteRef:
      key: test-dev2/sample-app-secret
      property: database.password
---
# ExternalSecret for database secrets
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: database-secret
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: database-secret
    type: Opaque
  data:
  - secretKey: host
    remoteRef:
      key: test-dev2/database-secret
      property: host
  - secretKey: port
    remoteRef:
      key: test-dev2/database-secret
      property: port
  - secretKey: database
    remoteRef:
      key: test-dev2/database-secret
      property: database
  - secretKey: username
    remoteRef:
      key: test-dev2/database-secret
      property: username
  - secretKey: password
    remoteRef:
      key: test-dev2/database-secret
      property: password
---
# ExternalSecret for API keys
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: api-keys-secret
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: api-keys-secret
    type: Opaque
  data:
  - secretKey: stripe-secret-key
    remoteRef:
      key: test-dev2/api-keys
      property: stripe_secret_key
  - secretKey: sendgrid-api-key
    remoteRef:
      key: test-dev2/api-keys
      property: sendgrid_api_key
  - secretKey: redis-password
    remoteRef:
      key: test-dev2/api-keys
      property: redis_password 